# The name of this site
# This text displays in the back-office and
# can be used in templates through the site.name global variable
name: Wisdom for Wanderers

# The site's subdomain
# This option is for sites on multi-site engines
# The value determines where the site can be accessed under the engine's primary domain
subdomain: wisdom_for_wanderers

# An array of domain aliases for the site
# This option is for sites on multi-site engines
# domains: [www.example.com, example.com]

# An array of locales (languages) the site is available in
# The locale listed first is the site's default locale
# Locales are specified using ISO language codes
# Possible locales include: en, de, fr, pl, pt-BR, it, nl, nb, es, ru, et, ja, zh-CN
locales: [en, fr, de, ru, zh-CN]

# The site's timezone
# This converts the server's time to the site's time zone in templates
# The TimeZone class from Rail's ActiveSupport is used to interpret the string
# Sample timezone strings: Tokyo, Beijing, Moscow, Cairo, Paris, Pacific Time (US & Canada)
timezone: Paris

# For SEO purposes, sites may wish to add a relevant string to the <title> tag
# And include <meta type="keywords"> and <meta type="description">
# For this purpose you can set values for these variables here
# They can be accessed in templates through the site.seo_title, site.meta_keywords, and site.meta_description variables
seo_title:
  en: Wisdom for Wanderers
  fr: Sagesse pour Vagabonds
  de: Weisheit für Wanderers
  ru: Мудрость для передвижников
  zh-CN: "智慧的流浪者"
meta_keywords:
  en: "travel backpacking for budget adventurers"
  fr: "voyage en sac à dos pour aventuriers fauchés"
  de: "Reisen mit dem Rucksack fur preisbewusste Abenteurer"
  ru: "путешествовать альпинизмом для бюджетных авантюристов"
  zh-CN: "背包旅行预算的冒险家"
meta_description:
  en: "Learn about cool places to see abroad, interesting things to eat and little travel tips you won't believe you lived without"
  fr: "Découvrez des endroits sympas à voir à l'étranger, des choses intéressantes à manger, et des petites petites astuces de voyages dont vous ne pourrez plus vous passer."
  de: "Erfahren Sie mehr über coole Orte, im Ausland zu sehen, interessante Dinge zu essen und kleine Reisetipps Sie nicht glauben werden, dass Sie, ohne gelebt haben konnten"
  ru: "Узнайте о прохладных местах, чтобы увидеть за рубежом, интересные вещи, чтобы поесть и мало поездок путешествия вы не поверите, вы жили без"
  zh-CN: "了解阴凉的地方，看看国外，有趣的东西吃，小的旅游行程，你不会相信你的生活中没有"
